# Generated by Django 3.2.23 on 2024-01-15 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0012_cast_genres_movies'),
        ('ott_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry', models.DateField()),
                ('status', models.CharField(max_length=30)),
                ('plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.subscription')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ott_app.register')),
            ],
        ),
    ]
