# Generated by Django 3.2.23 on 2023-12-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year', models.DateField()),
                ('language', models.CharField(max_length=25)),
                ('video', models.FileField(upload_to='add_movies')),
            ],
        ),
    ]
