# Generated by Django 3.2.23 on 2023-12-12 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_genre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genre',
            new_name='Genres',
        ),
    ]
