# Generated by Django 3.2.23 on 2023-12-15 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_cast_songs_trailer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songs',
            name='singer',
        ),
    ]
