# Generated by Django 3.2.23 on 2023-12-27 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0007_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='movie_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.movies'),
        ),
    ]
