# Generated by Django 3.2.23 on 2023-12-28 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0008_cast_movie_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='genres',
            name='movie_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.movies'),
        ),
    ]
