# Generated by Django 3.2.23 on 2024-01-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0009_genres_movie_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trailer',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='video',
        ),
        migrations.AddField(
            model_name='movies',
            name='movie_video',
            field=models.FileField(blank=True, null=True, upload_to='add_movies'),
        ),
        migrations.AddField(
            model_name='movies',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters'),
        ),
        migrations.AddField(
            model_name='movies',
            name='trailer_video',
            field=models.FileField(blank=True, null=True, upload_to='add_trailer'),
        ),
    ]
