# Generated by Django 3.2.23 on 2024-01-02 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0010_auto_20240102_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genres',
            name='movie_name',
        ),
        migrations.DeleteModel(
            name='Cast',
        ),
        migrations.DeleteModel(
            name='Genres',
        ),
        migrations.DeleteModel(
            name='Movies',
        ),
    ]
